on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 3 * * 1'

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

name: build-caches
jobs:
  build-cache:
    name: build rust caches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'rust'
          shared-key: 'cache'

      - name: Test (to build cache)
        run: cargo test --features tests