on:
  push:
    branches:
      - master
jobs:
  release_builds:
    name: advent-of-code-2022
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: "!github.event.release.prerelease"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'rust'
          shared-key: 'cache'

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Toronto"
          timezoneMacos: "America/Toronto"
          timezoneWindows: "Eastern Standard Time"
  
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=version::$(date +%Y.%m.%d)"
          echo "::set-output name=githash::$(git rev-parse --short HEAD)"

      - name: Build
        run: cargo build --release

      - name: Move executable
        run: |
          npm install -g move-file-cli mkdirp
          mkdirp artifacts
          if [ "$RUNNER_OS" == "Windows" ]; then
            move-file target/release/advent-of-code-2022.exe artifacts/advent-of-code-2022-windows.exe
          elif [ "$RUNNER_OS" == "Linux" ]; then
            move-file target/release/advent-of-code-2022 artifacts/advent-of-code-2022-linux
          else
            move-file target/release/advent-of-code-2022 artifacts/advent-of-code-2022-mac
          fi
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          tag_name: "v${{ steps.vars.outputs.version }}-${{ steps.vars.outputs.githash }}"
          generate_release_notes: true